"""Add show_barcode to InvoiceTemplate

Revision ID: 7c5abf1c70a7
Revises: 
Create Date: 2025-09-14 00:26:30.784523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c5abf1c70a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('barcode_link', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('show_barcode', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user_transaction', schema=None) as batch_op:
        batch_op.drop_column('barcode_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barcode_link', sa.VARCHAR(length=300), nullable=True))

    with op.batch_alter_table('invoice_template', schema=None) as batch_op:
        batch_op.drop_column('show_barcode')
        batch_op.drop_column('barcode_link')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
